server:
  port: 8084
spring:
  application:
    name: seata-service-business
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.102:8848
        group: SEATA_GROUP
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.0.102:8848
  tx-service-group: demo-group
  service:
    vgroup-mapping:
      demo-group: default

