registry:
  type: nacos
  nacos:
    application: seata-server
    serverAddr: 192.168.0.102:8848
    group: SEATA_GROUP
    namespace:
    cluster: default
    username:
    password:
config:
  type: file
  file:
    name: file:/root/seata-config/file.yml