server:
  port: 8083
spring:
  application:
    name: sentinel-ribbon
  cloud:
    nacos:
      discovery:
        server-addr: server:8848
    sentinel:
      transport:
        dashboard: server:18080
management:
  endpoints:
    web:
      exposure:
        include: '*'
