FROM openjdk:8
ADD sentinel-dashboard-1.8.1.jar sentinel-dashboard.jar
EXPOSE 8080
CMD ["java", "-Dcsp.sentinel.dashboard.server=localhost:8080", "-Dproject.name=sentinel-dashboard", "-jar", "sentinel-dashboard.jar"]