spring:
  application:
    name: dubbo-nacos-provider
dubbo:
  scan:
    base-packages: com.demo.dubbo.provider.service
  registry:
    address: nacos://192.168.0.102:8848?username=nacos&password=nacos
  protocol:
    name: dubbo
    port: 20880
  metadata-report:
    address: nacos://192.168.0.102:8848