server:
  port: 8083
spring:
  application:
    name: seata-service-storage
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_storage
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.102:8848
        group: SEATA_GROUP
mybatis:
  mapper-locations: classpath:mapper/*.xml
seata:
  tx-service-group: demo-group
  service:
    vgroup-mapping:
      demo-group: default
    grouplist:
      default: 192.168.0.102:8091