server:
  port: 8082
spring:
  application:
    name: seata-service-account
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_account
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.102:8848
        group: SEATA_GROUP
mybatis:
  mapper-locations: classpath:mapper/*.xml
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.0.102:8848
  tx-service-group: demo-group
  service:
    vgroup-mapping:
      demo-group: default

