server:
  port: 8084
spring:
  application:
    name: sentinel-openfeign
  cloud:
    nacos:
      discovery:
        server-addr: server:8848
    sentinel:
      transport:
        dashboard: server:18080
      datasource:
        ds1:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'
